# br-metabase-maistodos

# TODO:
# 1. Detalhar documentação AWS Cloudformation de cada recurso utilizado
# 2. Usar ECS para montar o Cluster do Metabase
# 3. Criar o Escalonamento do ECS via Cloudwatch de forma horizontal
# 4. Subredes diferentes entre Metabase (Subrede Publica) e Database Redshift (Subrede Privada)
# 5. Deverá ter um CI/CD e de forma automatizada para entrega do Metabase (Fazer numa stack a parte?)
# 6. Disponibilizar o link ao metabase
# 7. Descrever quais foram os desafios encontrados no caminho e soluções

# URLs de referencia:
# VPC: https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html
# Subnet: https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html
# 


Parameters:
  EnvironmentName:
  Type: String
  Default: "MaisTodos"

  PublicSubnetCIDR:
    Type: String
    Default: 10.192.10.0/24
  
  PrivateSubnetCIDR:
    Type: String
    Default: 10.192.20.0/24


Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnetCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnetCIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet

  


  